spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        format_sql: true
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address:${server.port}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka 

management:
  endpoints:
    web:
      exposure:
        include: "*"
